name: RabbiFourneau
main: rabbitown.bukkit.fourneau.RabbiFourneau
version: ${version}

api-version: 1.14

commands:
  rabbi-fourneau:
    aliases: [ rf, rfo, rfu ]

permissions:
  rabbitown.fourneau.give:
    default: op
